from typing import AsyncIterator, Protocol

from ..models import ProcessIdentity, ScreenFrame, SessionRef


class TerminalAdapter(Protocol):
    async def check_liveness(self, expected: ProcessIdentity) -> None: ...
    async def list_sessions(self) -> list[SessionRef]: ...
    async def probe(self, session_id: str) -> dict: ...
    async def capture(self, session_id: str) -> ScreenFrame: ...
    async def identity(self, session_id: str, allowed_paths: tuple[str, ...],
                       expected: ProcessIdentity | None = None) -> ProcessIdentity: ...
    def activities(self, session_id: str) -> AsyncIterator[None]: ...
    async def guarded_type(self, binding, event, text: str, latch_token: tuple) -> None: ...
    async def guarded_submit(self, binding, event, text: str, latch_token: tuple) -> None: ...
    async def close(self) -> None: ...
